services:
  entsoe-service:
    image: "${REGISTRY_APPLICATION}-app:${IMAGE_TAG}"
    build:
      dockerfile: ./docker/app/Dockerfile
      context: ..
      tags:
        - "${REGISTRY_APPLICATION}-app:latest"
        - "${REGISTRY_APPLICATION}-app:${IMAGE_TAG}"
    ports:
      - "9090:8080"
    depends_on:
      - entsoe-db
      - entsoe-ke-service
    env_file:
      - path: "./../resources/.env"
        required: true # default
      - path: "./../resources/env/.env.tm"
        required: true # default
    environment:
      #      - KE_REST_ENDPOINT=https://bluebird:WVOvwb3glJIFy0@ke-test-bluebird.apps.bst2.paas.psnc.pl/ke-test-runtime/rest/
      - KE_REST_ENDPOINT=http://entsoe-ke-service:8280/rest/
  #      - DB_HOST="${PROJECT_NAME}-${DB_HOST}"
    networks:
      - entsoe-net
  entsoe-db:
    image: ${REGISTRY_DOMAIN}/base/bitnami/postgresql:17.4.0-debian-12-r13
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
    networks:
      - entsoe-net
  entsoe-db-adminer:
    #    profiles: [dev, debug, prod]
    #    container_name: tge-db-adminer
    #    container_name: "${PROJECT_NAME}-${DB_HOST}"
    image: adminer:latest
    restart: always
    depends_on:
      - entsoe-db
    ports:
      - 9199:8080
    networks:
      - entsoe-net
#    networks:
#      - gnet
#    environment:
#      DOCKER_DEFAULT_PLATFORM: linux/amd64
  entsoe-ke-service:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.4.0
    environment:
      KE_RUNTIME_PORT: 8280
    ports:
      - 8280:8280
    networks:
      - entsoe-net
networks:
  entsoe-net:
    driver: bridge